feat: 成功ジョブの結果を確認するステップを追加 (#115)
* feat: 成功ジョブの結果を確認するステップを追加

- pull-request-other.yaml: 成功ジョブの結果を確認するステップを追加し、ドキュメントチェックの結果に基づいてメッセージを出力するように変更
- terraform-pull-request.yaml: 成功ジョブの結果を確認するステップを追加し、Terraformプランの結果に基づいてメッセージを出力するように変更
- web-deploy-staging.yaml: 成功ジョブの結果を確認するステップを追加し、ウェブステージングデプロイメントの結果に基づいてメッセージを出力するように変更

* feat: ジョブ結果のチェック条件を更新

- pull-request-other.yaml: 成功またはスキップされた場合にドキュメントチェックが成功したと見なすように条件を変更
- terraform-pull-request.yaml: 成功またはスキップされた場合にTerraformプランが成功したと見なすように条件を変更
- web-deploy-staging.yaml: 成功またはスキップされた場合にウェブステージングデプロイが成功したと見なすように条件を変更

* Merge branch 'main' into feat_update_branch_protection_checker

diff --git a/.github/workflows/pull-request-other.yaml b/.github/workflows/pull-request-other.yaml
--- a/.github/workflows/pull-request-other.yaml
+++ b/.github/workflows/pull-request-other.yaml
@@ -52,8 +52,17 @@ jobs:
 
   success:
     needs: check-documentation
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.check-documentation.result }}"
+          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
+            echo "Documentation check succeeded!"
+            exit 0
+          else
+            echo "Documentation check failed or was cancelled!"
+            exit 1
+          fi
diff --git a/.github/workflows/terraform-pull-request.yaml b/.github/workflows/terraform-pull-request.yaml
--- a/.github/workflows/terraform-pull-request.yaml
+++ b/.github/workflows/terraform-pull-request.yaml
@@ -113,8 +113,17 @@ jobs:
 
   success:
     needs: plan
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.plan.result }}"
+          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
+            echo "Terraform plan succeeded or was skipped (no targets)!"
+            exit 0
+          else
+            echo "Terraform plan failed or was cancelled!"
+            exit 1
+          fi
diff --git a/.github/workflows/web-deploy-staging.yaml b/.github/workflows/web-deploy-staging.yaml
--- a/.github/workflows/web-deploy-staging.yaml
+++ b/.github/workflows/web-deploy-staging.yaml
@@ -110,9 +110,18 @@ jobs:
 
   success:
     needs: deploy-staging
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.deploy-staging.result }}"
+          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
+            echo "Web staging deployment succeeded!"
+            exit 0
+          else
+            echo "Web staging deployment failed or was cancelled!"
+            exit 1
+          fi
 
