feat: 成功ジョブの結果を確認するステップを追加
- pull-request-other.yaml: 成功ジョブの結果を確認するステップを追加し、ドキュメントチェックの結果に基づいてメッセージを出力するように変更
- terraform-pull-request.yaml: 成功ジョブの結果を確認するステップを追加し、Terraformプランの結果に基づいてメッセージを出力するように変更
- web-deploy-staging.yaml: 成功ジョブの結果を確認するステップを追加し、ウェブステージングデプロイメントの結果に基づいてメッセージを出力するように変更

diff --git a/.github/workflows/terraform-pull-request.yaml b/.github/workflows/terraform-pull-request.yaml
--- a/.github/workflows/terraform-pull-request.yaml
+++ b/.github/workflows/terraform-pull-request.yaml
@@ -113,8 +113,16 @@ jobs:
 
   success:
     needs: plan
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          if [[ "${{ needs.plan.result }}" == "success" ]]; then
+            echo "Terraform plan succeeded!"
+            exit 0
+          else
+            echo "Terraform plan failed or was cancelled!"
+            exit 1
+          fi
diff --git a/.github/workflows/web-deploy-staging.yaml b/.github/workflows/web-deploy-staging.yaml
--- a/.github/workflows/web-deploy-staging.yaml
+++ b/.github/workflows/web-deploy-staging.yaml
@@ -110,9 +110,17 @@ jobs:
 
   success:
     needs: deploy-staging
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          if [[ "${{ needs.deploy-staging.result }}" == "success" ]]; then
+            echo "Web staging deployment succeeded!"
+            exit 0
+          else
+            echo "Web staging deployment failed or was cancelled!"
+            exit 1
+          fi
 
